<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Azure.AI.Inference" Version="1.0.0-beta.5" />
    <PackageVersion Include="Azure.AI.OpenAI" Version="2.1.0" />
    <PackageVersion Include="GeoTimeZone" Version="6.1.0" />
    <PackageVersion Include="Microsoft.Agents.AI" Version="1.1.0" />
    <PackageVersion Include="Microsoft.Agents.AI.Abstractions" Version="1.1.0" />
    <PackageVersion Include="Microsoft.Agents.AI.OpenAI" Version="1.1.0" />
    <PackageVersion Include="Microsoft.Agents.AI.Workflows" Version="1.1.0" />
    <PackageVersion Include="Microsoft.Extensions.AI.AzureAIInference" Version="10.0.0-preview.1.25559.3" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.5" />
    <PackageVersion Include="OllamaSharp" Version="5.4.25" />
    <PackageVersion Include="OpenWeatherMapSharp" Version="4.2.0" />
    <PackageVersion Include="Spectre.Console" Version="0.55.0" />
  </ItemGroup>
</Project>
