<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>8a2caaf4-9dc1-4add-81a6-0974d1e78c82</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.Inference" />
    <PackageReference Include="Azure.AI.OpenAI" />
    <PackageReference Include="GeoTimeZone" />
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.Agents.AI.Abstractions" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" />
    <PackageReference Include="Microsoft.Agents.AI.Workflows" />
    <PackageReference Include="Microsoft.Extensions.AI.AzureAIInference" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="OllamaSharp" />
    <PackageReference Include="OpenWeatherMapSharp" />
    <PackageReference Include="Spectre.Console" />
  </ItemGroup>

</Project>
